name: TestOgNetworkPlugin
version: 1.0
main: com.ognetwork.teamchat.TestOgNetWorkPlugin
api-version: 1.21
commands:
  redis:
    description: Configures Redis connection
    usage: /<command> <host> <port> <password>
  team:
    description: Manages teams
    usage: /<command> <create/join/leave> [teamName]
  teamchat:
    description: Sends a message to your team chat
    usage: /<command> <message>
